### ISSUE TITLE
Help with implementing in a react project.

### ISSUE THREAD

**Issue by HumidBrains** [meodai/poline#20]
@meodai I'd be very grateful for any pointers on how to implement Poline in react. I've tried for an eternity, but I'm simply too stupid to figure it out. I don't expect your time to be for free. ;)

**Comment by meodai** [comment]
hey! what specific feature are you trying to implement?

**Comment by HumidBrains** [comment]
Hey David, thanks for such quick reply and for your example :) However, the palette colours I've managed to render myself, I should have mentioned that. It's your brilliant colour wheel I don't manage to render. I think you've built such an intuitive way to select palette colours and I have to say you're simply a colour genius. I was looking to implement both the colour wheel and the palette into a cms project that runs on Next.js. 

I've seen that you render the wheel with p5, but I haven't managed to get it working in react. Any input on that?

**Comment by meodai** [comment]
the wheel itself is not part of the lib. Not sure to do this cleanly, especially if it needs to work with all kinds of libs. But its not too complex to build for a specific lib

**Comment by HumidBrains** [comment]
To me the UX provided by the wheel is what really sets poline apart and make it so intuitive. I'd love to discuss with you how we can make it run in react.

**Comment by meodai** [comment]
@HumidBrains Hey I am sorry but I am quite busy with my current project. Feel free to hit me up again in a few weeks.
