### ISSUE TITLE
 TypeError: undefined is not a constructor (evaluating 'new (_$$_REQUIRE(_dependencyMap[15], "poline").Poline)(options)')

### ISSUE THREAD

**Issue by Reagankm** [meodai/poline#4]
I added poline to my react-native project with `yarn add poline` and that seemed to install it correctly. it added `"poline": "^0.5.1",` to my package.json. I restarted Metro and rebuilt my app.

In my file, though, I get that Typescript "undefined is not a constructor" error when I do this:

```
import { Poline, PolineOptions } from 'poline';
...
const options: PolineOptions = {
            anchorColors: [
                [273, 0.91, 0.69], //light purple
                [173, 0.36, .046] //teal
            ],
            numPoints: 4,
            closedLoop: false,
        };
        const poline = new Poline(options);
```

I'm coding in Intellij and I can command-click on the Poline constructor which takes me to the source in dist/index.d.ts where I can see there is indeed a constructor.  

I'm sure I'm missing some simple step here.  Any idea what I'm doing wrong?

**Comment by meodai** [comment]
lgtm, what bundler are you using?

**Comment by meodai** [comment]
@Reagankm this might help in the meantime: https://twitter.com/d_rx/status/1623087797551742977

**Comment by dirx** [comment]
I tried again and removed and reinstalled poline 0.5.1 > it now works for me again. I think I had a different issue.

This issue looks more like bundling poline is not working correctly.

**Comment by Reagankm** [comment]
@meodai There's definitely something wrong with my setup. If I try console logging Poline right after the import it's undefined:

```
import { Poline } from 'poline';
console.log(Poline);
```

I'm pretty sure the bundler is just Metro which comes with react-native. (Though maybe I'm misunderstanding your question.)

I'm going to try doing a complete clean and rebuild. This feels like some shitty config issue on my end

**Comment by meodai** [comment]
Don't hesitate to reopen an Issue if you encounter problems again
