### ISSUE TITLE
Website does not load on Firefox

### ISSUE THREAD

**Issue by Gazook89** [meodai/poline#5]
I first viewed this on iOS without issue (firefox but webkit), but now on macOS Firefox the page does not load anything.  The error in the console:

```
Uncaught SyntaxError: ambiguous indirect export: default         poline:1379:11
```

Works fine in macOS Chrome.

(Really excellent work, btw.  Love it).

**Comment by meodai** [comment]
@Gazook89 maybe you have an old version of FF then. Works just fine on my side
<img width="1624" alt="Screenshot 2023-02-10 at 09 02 01" src="https://user-images.githubusercontent.com/608386/218035691-0f4f4e75-8c94-4d9e-be96-a80a4760018c.png">

**Comment by Gazook89** [comment]
Ah, sorry it was my LocalCDN extension that was blocking it.  Turned that off and we're good to go.  Closing!

**Comment by meodai** [comment]
@Gazook89 no worries. I am glad you can  now enjoy it on desktop. Have fun
